//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashAnimations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashAnimations.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Animations&gt;
        ///  &lt;Animation name=&quot;god_scores_intro&quot; frameCount=&quot;44&quot;&gt;
        ///    &lt;Part name=&quot;cloudback&quot;&gt;
        ///      &lt;Frame x=&quot;-21.05&quot; y=&quot;282.90&quot; scaleX=&quot;0.093&quot; scaleY=&quot;0.093&quot; index=&quot;0&quot;/&gt;
        ///      &lt;Frame x=&quot;-21.00&quot; y=&quot;282.90&quot; scaleX=&quot;0.093&quot; scaleY=&quot;0.093&quot; index=&quot;1&quot;/&gt;
        ///      &lt;Frame x=&quot;-21.00&quot; y=&quot;282.90&quot; scaleX=&quot;0.093&quot; scaleY=&quot;0.093&quot; index=&quot;2&quot;/&gt;
        ///      &lt;Frame x=&quot;-21.00&quot; y=&quot;282.90&quot; scaleX=&quot;0.093&quot; scaleY=&quot;0.093&quot; index=&quot;3&quot;/&gt;
        ///      &lt;Frame x=&quot;-21.00&quot; y=&quot;282.90&quot; scaleX=&quot;0.093&quot; scaleY=&quot;0.093&quot; index=&quot;4&quot;/&gt;
        ///      &lt;Frame x=&quot;-21.00&quot; y=&quot;282.9 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string animations {
            get {
                return ResourceManager.GetString("animations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Textures&gt;
        ///  &lt;TextureSheet name=&quot;darwinsheet&quot;&gt;
        ///    &lt;Texture name=&quot;darwin&quot; width=&quot;484&quot; height=&quot;714&quot; path=&quot;darwinsheet/darwin.png&quot; registrationPointX=&quot;64.00&quot; registrationPointY=&quot;100.00&quot; frameCount=&quot;28&quot; frameWidth=&quot;121&quot; frameHeight=&quot;102&quot; columns=&quot;4&quot;/&gt;
        ///  &lt;/TextureSheet&gt;
        ///  &lt;TextureSheet name=&quot;godscores&quot;&gt;
        ///    &lt;Texture name=&quot;text&quot; width=&quot;320&quot; height=&quot;191&quot; path=&quot;godscores/text.png&quot; registrationPointX=&quot;140.00&quot; registrationPointY=&quot;80.00&quot; zIndex=&quot;4&quot;/&gt;
        ///    &lt;Texture name=&quot;cloudfront&quot; width=&quot;341&quot; height=&quot;249&quot; path=&quot;godsc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sheets {
            get {
                return ResourceManager.GetString("sheets", resourceCulture);
            }
        }
    }
}
